1. Created PaymentOS account with secure password. 
2. To create Providers and BusinessUnits, I followed: https://developers.paymentsos.com/docs/getting-started/setting-up-paymentsos.html
+ Selected Configurations > Providers > Mock Provider  with testing name (entity for which transactions are executed).
+ Selected Configurations > BusinessUnits > Create Business Unit > created "ecomoda" business unit with Mock Provider.
App ID: com.nicolasgomezaragon7@gmail.ecomoda
Public_API_Key: 7c64be3c-5914-44dd-a6af-02fbd16e25ab
Private_API_Key: f5366c4a-8d89-4c0c-9f64-b3433adeaa3c

+ Importing collection to Postman and modified AppID and PriavteAPIKey, info found on: https://developers.paymentsos.com/docs/getting-started/give-it-a-try.html

+ Configure headers and set x-payments-os-env to 'test', run POST to execute payment and got:  
Status 201 CREATED with "id": "33002d5b-c860-4d0f-97f8-eca55763cfcb",

+ Before proceeding, configured global variables for PrivateAPIKey and AppID, right sidebar.

+ Verified that authorization was succesful with 201 code, output:
    "id": "2dfd701e-110b-40b0-af8e-f1f2df64b990",
    "created": "1746716594203",
    "reconciliation_id": "23434534534",

+ Using PaymentId: "33002d5b-c860-4d0f-97f8-eca55763cfcb",
capture was completed with   "id": "b2f0e7d9-cfc0-4647-b844-a9592efdffe2".

However, got:
 "result": {
        "status": "Failed",
        "category": "provider_error",
        "description": "Something went wrong on the provider's side."
    },

+ Trying all over again:
CREATE TOKEN
9afae9db-0056-43ce-a7de-9b857d925bba
CREATE PAYMENT
92f2e976-38b4-4fe3-8f8e-5d3eeba4bb9b
CREATE AUTHORIZATION
3b1b1bce-818f-407c-8dfe-e8153b4fb794

FAILURE DUE TO 
more_info	"Unauthorized for actions on live environment"
category	"api_authentication_error"
description	"We were unable to authenticate your request."

Still got, $19 EUR on account. 

+ Review PaymentOS config and everything seems right. run again commands, this time using amounts in Cents, thefore $64000 USD.
CREATE TOKEN
db1f843c-c516-40ba-b9e5-9efca36c2aef
CREATE PAYMENT
76cfdbf1-c9f2-47d3-9f9c-cd423544f5ee
CREATE AUTHORIZATION
4c7cd2b1-8d39-47ac-be68-417fd912ee3d
CREATE CAPTURE 
3e40a751-4c25-427b-90b6-72e6786ebd4f

Most probably error was due to the token, I was using EUR, although token was being generated by a US card.

Proceeding with refund 
TOKEN: 9c8709e7-0928-4232-9661-e972a6affb2a
REFUND: 779a17fe-bbcb-40ab-90b0-7c55ecf0cee6

Tokenization wasn't required for the refund, still got it, just needed payment_id, output with Status 201 created: 
{
    "id": "779a17fe-bbcb-40ab-90b0-7c55ecf0cee6",
    "created": "1746718564212",
    "result": {
        "status": "Succeed"
    },
    "provider_data": {
        "provider_name": "MockProcessor",
        "response_code": "0",
        "description": "Refunded.",
        "raw_response": "{\"OID\":\"76cfdbf1-c9f2-47d3-9f9c-cd423544f5ee\",\"AUTH_CODE\":\"76cfd\",\"RETURN_MESSAGE\":\"Refunded.\",\"TRANSID\":\"9031176e-5fb3-51c8-915c-085b69efbf06_60b805a3-ea92-4bc3-b22c-a801b27e0986_Refund\",\"STATUS\":\"SUCCESS\",\"AMOUNT\":\"640\",\"DATE\":\"1746718564212\",\"RETURN_CODE\":\"0\",\"CURRENCY\":\"USD\"}",
        "authorization_code": "76cfd",
        "transaction_id": "9031176e-5fb3-51c8-915c-085b69efbf06_60b805a3-ea92-4bc3-b22c-a801b27e0986_Refund",
        "external_id": "76cfdbf1-c9f2-47d3-9f9c-cd423544f5ee"
    },
    "amount": 64000,
    "provider_configuration": {
        "id": "d38520d4-28a3-41e4-81df-baa0b62e9d03",
        "name": "testing",
        "description": "TestEnv",
        "created": "1746713343213",
        "modified": "1746713343213",
        "account_id": "60b805a3-ea92-4bc3-b22c-a801b27e0986",
        "provider_id": "c87ee096-e1a4-4502-9194-9e9b6e867bf0",
        "type": "cc_processor",
        "href": "https://api.paymentsos.com/accounts/60b805a3-ea92-4bc3-b22c-a801b27e0986/provider-configurations/d38520d4-28a3-41e4-81df-baa0b62e9d03"
    }
}

